-- First-party pilot measurement only. Store event facts, not household
-- content: no capture text, titles, email addresses, URLs, or message bodies.
create table if not exists public.pilot_events (
    id bigint generated by default as identity primary key,
    household_id uuid not null references public.households(id) on delete cascade,
    actor uuid references auth.users(id) on delete set null,
    event_name text not null check (event_name in (
        'household_created',
        'member_invited',
        'member_active',
        'dashboard_opened',
        'capture_created',
        'capture_converted',
        'task_completed',
        'briefing_opened',
        'briefing_acted_on',
        'conflict_resolved',
        'subscription_started',
        'subscription_cancelled',
        'subscription_renewed'
    )),
    entity_type text,
    entity_id uuid,
    metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
    dedupe_key text check (dedupe_key is null or char_length(dedupe_key) between 1 and 160),
    occurred_at timestamptz not null default timezone('utc', now())
);

create index if not exists pilot_events_household_time_idx
    on public.pilot_events(household_id, occurred_at desc);
create index if not exists pilot_events_name_time_idx
    on public.pilot_events(event_name, occurred_at desc);
create unique index if not exists pilot_events_dedupe_idx
    on public.pilot_events(household_id, event_name, dedupe_key)
    where dedupe_key is not null;

alter table public.pilot_events enable row level security;
revoke select, insert, update, delete on public.pilot_events from public, anon, authenticated, service_role;

create or replace function public.record_pilot_event(
    p_actor_user_id uuid,
    p_household_id uuid,
    p_event_name text,
    p_entity_type text default null,
    p_entity_id uuid default null,
    p_metadata jsonb default '{}'::jsonb,
    p_dedupe_key text default null
)
returns setof public.pilot_events
language plpgsql
security definer
set search_path = public
as $$
declare
    event_row public.pilot_events;
    event_metadata jsonb := '{}'::jsonb;
begin
    if p_actor_user_id is null then
        raise exception 'actor is required' using errcode = '42501';
    end if;
    if not exists (
        select 1
        from public.memberships
        where household_id = p_household_id
          and user_id = p_actor_user_id
        for update
    ) then
        raise exception 'household membership required' using errcode = '42501';
    end if;
    if p_event_name not in (
        'household_created',
        'member_invited',
        'member_active',
        'dashboard_opened',
        'capture_created',
        'capture_converted',
        'task_completed',
        'briefing_opened',
        'briefing_acted_on',
        'conflict_resolved',
        'subscription_started',
        'subscription_cancelled',
        'subscription_renewed'
    ) then
        raise exception 'unsupported pilot event' using errcode = '22023';
    end if;
    if p_metadata is null or jsonb_typeof(p_metadata) <> 'object' then
        raise exception 'pilot metadata must be an object' using errcode = '22023';
    end if;

    if p_event_name in ('household_created', 'member_active', 'dashboard_opened', 'task_completed', 'briefing_opened', 'briefing_acted_on', 'conflict_resolved')
       and p_metadata->>'source' in ('setup', 'dashboard', 'email', 'photon', 'notification', 'client', 'unknown') then
        event_metadata := event_metadata || jsonb_build_object('source', p_metadata->>'source');
    end if;
    if p_event_name = 'member_invited'
       and p_metadata->>'role' in ('member', 'child', 'guest') then
        event_metadata := event_metadata || jsonb_build_object('role', p_metadata->>'role');
    end if;
    if p_event_name = 'capture_created' then
        if p_metadata->>'source' in ('setup', 'dashboard', 'email', 'photon', 'notification', 'client', 'unknown') then
            event_metadata := event_metadata || jsonb_build_object('source', p_metadata->>'source');
        end if;
        if jsonb_typeof(p_metadata->'private') = 'boolean' then
            event_metadata := event_metadata || jsonb_build_object('private', p_metadata->'private');
        end if;
    end if;
    if p_event_name = 'capture_converted'
       and p_metadata->>'conversion_type' in ('task', 'event', 'meal', 'grocery') then
        event_metadata := event_metadata || jsonb_build_object('conversion_type', p_metadata->>'conversion_type');
    end if;
    if p_event_name = 'briefing_acted_on'
       and p_metadata->>'action' in ('task_completed', 'grocery_opened', 'calendar_opened', 'dismissed', 'unknown') then
        event_metadata := event_metadata || jsonb_build_object('action', p_metadata->>'action');
    end if;
    if p_event_name = 'conflict_resolved'
       and p_metadata->>'resolution' in ('accepted', 'dismissed', 'snoozed', 'unknown') then
        event_metadata := event_metadata || jsonb_build_object('resolution', p_metadata->>'resolution');
    end if;
    if p_event_name in ('subscription_started', 'subscription_cancelled', 'subscription_renewed')
       and p_metadata->>'plan' in ('pilot', 'monthly', 'annual', 'unknown') then
        event_metadata := event_metadata || jsonb_build_object('plan', p_metadata->>'plan');
    end if;

    if p_dedupe_key is null then
        insert into public.pilot_events (household_id, actor, event_name, entity_type, entity_id, metadata)
        values (p_household_id, p_actor_user_id, p_event_name, p_entity_type, p_entity_id, event_metadata)
        returning * into event_row;
    else
        insert into public.pilot_events (household_id, actor, event_name, entity_type, entity_id, metadata, dedupe_key)
        values (p_household_id, p_actor_user_id, p_event_name, p_entity_type, p_entity_id, event_metadata, p_dedupe_key)
        on conflict (household_id, event_name, dedupe_key) where dedupe_key is not null do nothing
        returning * into event_row;
        if not found then
            select * into event_row
            from public.pilot_events
            where household_id = p_household_id
              and event_name = p_event_name
              and dedupe_key = p_dedupe_key
            order by id desc
            limit 1;
        end if;
    end if;

    if event_row.id is not null then
        return next event_row;
    end if;
    return;
end;
$$;

revoke all on function public.record_pilot_event(uuid, uuid, text, text, uuid, jsonb, text) from public, anon, authenticated;
grant execute on function public.record_pilot_event(uuid, uuid, text, text, uuid, jsonb, text) to service_role;
