create extension if not exists pgcrypto;

create table if not exists public.households (
    id uuid primary key default gen_random_uuid(),
    name text not null check (char_length(trim(name)) between 1 and 120),
    created_by uuid not null references auth.users(id) on delete restrict,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.memberships (
    household_id uuid not null references public.households(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    role text not null check (role in ('owner', 'member', 'child', 'guest')),
    created_at timestamptz not null default timezone('utc', now()),
    primary key (household_id, user_id)
);

create table if not exists public.inbox_items (
    id uuid primary key default gen_random_uuid(),
    household_id uuid not null references public.households(id) on delete cascade,
    original_text text not null check (char_length(trim(original_text)) between 1 and 4000),
    source text not null default 'dashboard' check (char_length(source) between 1 and 80),
    private boolean not null default false,
    status text not null default 'open' check (status in ('open', 'archived', 'converted')),
    converted_type text,
    converted_id uuid,
    created_by uuid not null references auth.users(id) on delete restrict,
    created_at timestamptz not null default timezone('utc', now()),
    resolved_at timestamptz
);

create table if not exists public.tasks (
    id uuid primary key default gen_random_uuid(),
    household_id uuid not null references public.households(id) on delete cascade,
    title text not null check (char_length(trim(title)) between 1 and 500),
    due_at timestamptz,
    owner uuid references auth.users(id) on delete set null,
    assignee uuid references auth.users(id) on delete set null,
    private boolean not null default false,
    recurrence text not null default 'none' check (recurrence in ('none', 'daily', 'weekly', 'fortnightly', 'monthly', 'yearly')),
    status text not null default 'open' check (status in ('open', 'done', 'archived')),
    created_by uuid not null references auth.users(id) on delete restrict,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.events (
    id uuid primary key default gen_random_uuid(),
    household_id uuid not null references public.households(id) on delete cascade,
    title text not null check (char_length(trim(title)) between 1 and 500),
    starts_at timestamptz not null,
    ends_at timestamptz,
    person text,
    assignee uuid references auth.users(id) on delete set null,
    status text not null default 'confirmed' check (status in ('confirmed', 'cancelled')),
    created_by uuid not null references auth.users(id) on delete restrict,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.meals (
    id uuid primary key default gen_random_uuid(),
    household_id uuid not null references public.households(id) on delete cascade,
    meal_date date not null,
    meal_type text not null check (meal_type in ('breakfast', 'lunch', 'dinner')),
    title text not null check (char_length(trim(title)) between 1 and 500),
    cook uuid references auth.users(id) on delete set null,
    status text not null default 'planned' check (status in ('planned', 'served', 'archived')),
    ingredients jsonb not null default '[]'::jsonb check (jsonb_typeof(ingredients) = 'array'),
    created_by uuid not null references auth.users(id) on delete restrict,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.grocery_items (
    id uuid primary key default gen_random_uuid(),
    household_id uuid not null references public.households(id) on delete cascade,
    name text not null check (char_length(trim(name)) between 1 and 300),
    quantity numeric not null default 1 check (quantity > 0),
    unit text not null default 'each',
    category text not null default 'General',
    price numeric(10, 2) check (price is null or price >= 0),
    price_source text,
    price_url text,
    price_checked_at timestamptz,
    price_confidence text,
    price_note text,
    status text not null default 'open' check (status in ('open', 'archived')),
    created_by uuid not null references auth.users(id) on delete restrict,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.activity_log (
    id bigint generated by default as identity primary key,
    household_id uuid not null references public.households(id) on delete cascade,
    actor uuid references auth.users(id) on delete set null,
    action text not null,
    entity_type text not null,
    entity_id uuid,
    before_json jsonb,
    after_json jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    undone_at timestamptz
);

create index if not exists memberships_user_id_idx on public.memberships(user_id);
create index if not exists inbox_items_household_status_idx on public.inbox_items(household_id, status, created_at desc);
create index if not exists tasks_household_status_due_idx on public.tasks(household_id, status, due_at);
create index if not exists events_household_starts_idx on public.events(household_id, starts_at);
create index if not exists meals_household_date_idx on public.meals(household_id, meal_date);
create index if not exists grocery_items_household_status_idx on public.grocery_items(household_id, status);
create index if not exists activity_log_household_created_idx on public.activity_log(household_id, created_at desc);

create or replace function public.is_household_member(target_household_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
    select exists (select 1 from public.memberships where household_id = target_household_id and user_id = (select auth.uid()));
$$;

create or replace function public.is_household_owner(target_household_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
    select exists (select 1 from public.memberships where household_id = target_household_id and user_id = (select auth.uid()) and role = 'owner');
$$;

create or replace function public.create_household(household_name text)
returns public.households language plpgsql security definer set search_path = public as $$
declare created_household public.households;
begin
    if auth.uid() is null then raise exception 'authentication required' using errcode = '42501'; end if;
    if char_length(trim(coalesce(household_name, ''))) not between 1 and 120 then
        raise exception 'household name is required' using errcode = '22023';
    end if;
    insert into public.households (name, created_by) values (trim(household_name), auth.uid()) returning * into created_household;
    insert into public.memberships (household_id, user_id, role) values (created_household.id, auth.uid(), 'owner');
    return created_household;
end;
$$;

alter table public.households enable row level security;
alter table public.memberships enable row level security;
alter table public.inbox_items enable row level security;
alter table public.tasks enable row level security;
alter table public.events enable row level security;
alter table public.meals enable row level security;
alter table public.grocery_items enable row level security;
alter table public.activity_log enable row level security;
